[mypy]
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True
exclude = pacman|venv|.venv|__pycache__
plugins = pydantic.mypy

[mypy-mazegenerator.*]
ignore_errors = True